# Assignment 1 | 25th February 2021


### Question 1:
Given the following jumbled word, OBANWRI guess the correct English word.
    A. RANIBOW
    B. RAINBOW
    C. BOWRANI
    D. ROBWANI
    
Ans. (B)    

### Question 2:

Write a program that prints “LETS UPGRADE”. (Please note that you have to print in ALL CAPS
as given)

In [2]:
print("lets upgrade".upper())

LETS UPGRADE


### Question 3:

Write a program that takes cost price and selling price as input and
displays whether the transaction is a Profit or a Loss or Neither​ .
    INPUT FORMAT
        ● The first line contains the cost price.
        ● The second line contains the selling price.
    OUTPUT FORMAT
        ● Print "Profit" if the transaction is a profit or "Loss" if it is a loss. If it is neither
        ● profit nor loss, print "Neither". (You must not have quotes in your output)
        
NOTE: Please stick to the input and output format. Don't add anything extra like
'Enter cost price', 'Enter selling price', etc.
(Some part missing)

In [17]:
cost = int(input())
price = int(input())

if price >= cost * 1.5:
    print("Profit")
elif price <= (cost/2):
    print("Lost")
else:
    print("Neither")

20
30
Profit


### Question 4:

Write a program that takes an amount in Euros as input. You need to find its equivalent in
Rupees and display it. Assume 1 Euro equals Rs. 80.


Please note that you are expected to stick to the given input and output
format as in sample test cases. Please don't add any extra lines such as
'Enter a number’ etc.
Your program should take only one number as input and display the output.

In [27]:
euros = int(input())
rupees = euros*80
print(rupees)

18
1440


### Question 5:

Create an empty list. Accept 10 numbers from the user and append to it the list if it is an even
number.

In [43]:
lst = []
for i in range(10):
    inp = int(input())
    if inp%2==0:
        lst.append(inp)
print(lst)

20
30
49
48
47
46
28
10
20
42
[20, 30, 48, 46, 28, 10, 20, 42]


### Question 6:

Create a notebook on LIST COMPREHENSION. This exercise is to put you in a
Self-learning mode

In [47]:
[x**2 for x in range(10) if x%2==0]

[0, 4, 16, 36, 64]

In [49]:
[x+3 for x in range(21) if x%3==0]

[3, 6, 9, 12, 15, 18, 21]

In [56]:
[int(x/2) for x in range(1,10) if x%2==0]

[1, 2, 3, 4]

### Question 7:

You have seen in the videos how powerful dictionary data structure is.
In this assignment, given a number n, you have to write a program that generates a dictionary
d which contains (i, i*i), where i is from 1 to n (both included).
Then you have to just print this dictionary d.

In [63]:
n = int(input())
d = {}

for i in range(1, n+1):
    d[i]=i*i
print(d)

4
{1: 1, 2: 4, 3: 9, 4: 16}


### Questions 8:

There is a robot that wants to go to the charging point to charge itself.
The robot moves in a 2-D plane from the original point (0,0). The robot can
move toward UP, DOWN, LEFT, and RIGHT with given steps.
The trace of robot movement is shown as the following:
    UP 5
    DOWN 3
    LEFT 3
    RIGHT 2
Then, the output of the program should be: 2
The numbers after the direction are steps.
Write a program to compute the distance between the current position after
a sequence of movement and the original point. If the distance is float, then
just print the nearest integer (use round() function for that and then convert
it into an integer).
Input Format:
The first line of the input contains a number n which implies the number of
directions to be given.
The next n lines contain the direction and the step separated by a space.
Output Format:
Print the distance from the original position to the current position.
### Example:
    Input: 4
    UP 5
    DOWN 3
    LEFT 3
    RIGHT 2
    
### Output: 2

In [98]:
from math import sqrt
lst = []
position = [0,0]
while True:
    a = input()
    if not a:
        break
    lst.append(a)
for i in lst:
    if 'UP' in i:
        position[0] -= int(i.strip('UP '))
    if 'DOWN' in i:
        position[0] += int(i.strip('DOWN '))
    if 'LEFT' in i:
        position[1] -= int(i.strip('LEFT '))
    if 'RIGHT' in i:
        position[1] += int(i.strip('RIGHT '))
print(round(sqrt(position[1] ** 2 + position[0] ** 2)))

4
UP 5
DOWN 3
LEFT 3
RIGHT 2

2


### Questions 9:
Create a NumPy array starting from 2 till 50 with a step size of 3.

In [101]:
import numpy as np
arr = np.array(range(2,50,3))
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


### Questions 10:
Accept two lists of 5 elements each from the user.
Convert them to NumPy arrays. Concatenate these arrays and print them. Also, sort these arrays
and print them.

In [203]:
lst1 = []
lst2 = []
# Accepting elements from user and appending them to list
for i in range(5):
    lst1.append(input())
print(lst1)

for i in range(5):
    lst2.append(input())
print(lst2)

# converting list to array

import numpy as np
arr1 = np.array(lst1, dtype=int)
arr2 = np.array(lst2, dtype=int)
print()
print("Array 1st is :",arr1)
print("Array 2nd is :",arr2)

5
4
3
2
1
['5', '4', '3', '2', '1']
9
8
7
6
5
['9', '8', '7', '6', '5']

Array 1st is : [5 4 3 2 1]
Array 2nd is : [9 8 7 6 5]


In [204]:
# Concatenate two arrays

Concatenated_arr = np.concatenate((arr1, arr2), axis= 0)
print("Array after Concatenated: \n", Concatenated_arr)

Array after Concatenated: 
 [5 4 3 2 1 9 8 7 6 5]


In [205]:
# sorting above array
def selection(arr):
    for i in range(len(arr)):
        min_index = i
        for j in range(i+1, len(arr)):
            if arr[min_index] > arr[j]:
                min_index = j
        arr[i],arr[min_index] = arr[min_index],arr[i]
    print("Sorted array")
    print(arr)
selection(arr1)
selection(arr2)

Sorted array
[1 2 3 4 5]
Sorted array
[5 6 7 8 9]


### Questions 11:

Write a code snippet to find the dimensions of a ndarray and its size.

In [135]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Dimension of array :",arr.shape)
print("Size of array :",arr.size)

Dimension of array : (3, 3)
Size of array : 9


### Questions 12:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [147]:
# 1D array
arr = np.array([1,2,3,4,5])
print(arr)
# Confirm dimension of array
print(arr.shape)

# convert array in 2D array using np.newaxis
arr_new = arr[np.newaxis, :]
print(arr_new)
# Confirm dimension of array
print(arr_new.shape)

# convert array in 2D array using np.expand_dims

arr_Expanded = np.expand_dims(arr, axis=0)
print(arr_Expended)
# Confirm dimension of array 
print(arr_Expanded.shape)

[1 2 3 4 5]
(5,)
[[1 2 3 4 5]]
(1, 5)
[[1 2 3 4 5]]
(1, 5)


### Questions 13:

Consider two square NumPy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [164]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("First array is: \n", A)
print()
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Second array is: \n", B)

print()
# Vertically Stack
V = np.vstack((A,B))
print("Vertically stack of both arrays: \n", V)

print()

# Horizontally Stack

H = np.hstack((A,B))
print("Horizontally stack of both arrays: \n", H)

First array is: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Second array is: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Vertically stack of both arrays: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]

Horizontally stack of both arrays: 
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


### Questions 14:

How to get unique items and counts of unique items?

In [186]:
# consider a list

lst = [1,2,3,2,4,3,5,4,7,4,6,4]


# 1st way to get only unique values
u_lst = np.unique(lst)
print(u_lst)
print(len(u_lst))

# 2nd way to find unique 

unique_lst = []
count = 0
for i in lst:
    if i not in unique_lst:
        count = count+ 1
        unique_lst.append(i)
print(unique_lst)
print(count)

# 3rd way to find unique values 

a_set = set(lst)  # by converting list into set 
print(a_set) # printing set
print(len(a_set)) #printing length of set

[1 2 3 4 5 6 7]
7
[1, 2, 3, 4, 5, 7, 6]
7
{1, 2, 3, 4, 5, 6, 7}
7
